repos:
-  repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v4.1.0
   hooks:
   -  id: trailing-whitespace
   -  id: end-of-file-fixer
   -  id: pretty-format-json

-   repo: https://github.com/pycqa/flake8
    rev: 3.7.3
    hooks:
    -   id: flake8
        exclude: ^(src|tests)/.*

-  repo: https://github.com/pre-commit/mirrors-mypy
   rev: v1.0.1
   hooks:
   -  id: mypy
      args: [--follow-imports=skip, src, tests ]
